const CREATE_SERVICE_DETAIL_FAILED = 'CREATE_SERVICE_DETAIL_FAILED'
const GET_SERVICE_DETAILS_MONTH_FAILED = 'GET_SERVICE_DETAILS_MONTH_FAILED'
const GET_SERVICE_DETAILS_BY_OWNER_FAILED = 'GET_SERVICE_DETAILS_BY_OWNER_FAILED'
const GET_SERVICE_DETAIL_BY_ID_FAILED = 'GET_SERVICE_DETAIL_BY_ID_FAILED'
const UPDATE_SERVICE_DETAIL_FAILED = 'UPDATE_SERVICE_DETAIL_FAILED'
const DELETE_SERVICE_DETAIL_FAILED = 'DELETE_SERVICE_DETAIL_FAILED'

module.exports = {
    CREATE_SERVICE_DETAIL_FAILED,
    GET_SERVICE_DETAILS_MONTH_FAILED,
    GET_SERVICE_DETAILS_BY_OWNER_FAILED,
    GET_SERVICE_DETAIL_BY_ID_FAILED,
    UPDATE_SERVICE_DETAIL_FAILED,
    DELETE_SERVICE_DETAIL_FAILED
}