const CREATE_SERVICE_FAILED = 'CREATE_SERVICE_FAILED'
const SERVICE_NOT_OF_ROOM = 'SERVICE_NOT_OF_ROOM'
const NAME_SERVICE_EXIST = 'NAME_SERVICE_EXIST'
const GET_SERVICES_BY_BLOCK_FAILED = 'GET_SERVICES_BY_BLOCK_FAILED'
const GET_SERVICE_BY_ID_FAILED = 'GET_SERVICE_BY_ID_FAILED'
const UPDATE_SERVICE_FAILED = 'UPDATE_SERVICE_FAILED'
const DELETE_SERVICE_FAILED = 'DELETE_SERVICE_FAILED'

module.exports = {
    CREATE_SERVICE_FAILED,
    SERVICE_NOT_OF_ROOM,
    NAME_SERVICE_EXIST,
    GET_SERVICES_BY_BLOCK_FAILED,
    GET_SERVICE_BY_ID_FAILED,
    UPDATE_SERVICE_FAILED,
    DELETE_SERVICE_FAILED
}