const CREATE_ROOM_FAILED = 'CREATE_ROOM_FAILED'
const NAME_ROOM_EXIST = 'NAME_ROOM_EXIST'
const GET_BLOCK_ROOM_FAILED = 'GET_BLOCK_ROOM_FAILED'
const GET_ROOM_BY_ID_FAILED = 'GET_ROOM_BY_ID_FAILED'
const GET_ROOMS_BY_CUSTOMER_FAILED = 'GET_ROOMS_BY_CUSTOMER_FAILED'
const UPDATE_ROOM_FAILED = 'UPDATE_ROOM_FAILED'
const DELETE_ROOM_FAILED = 'DELETE_ROOM_FAILED'

module.exports = {
    CREATE_ROOM_FAILED,
    NAME_ROOM_EXIST,
    GET_BLOCK_ROOM_FAILED,
    GET_ROOM_BY_ID_FAILED,
    GET_ROOMS_BY_CUSTOMER_FAILED,
    UPDATE_ROOM_FAILED,
    DELETE_ROOM_FAILED
}