const CREATE_CUSTOMER_FAILED = 'CREATE_CUSTOMER_FAILED'
const ROOM_IS_FULL = 'ROOM_IS_FULL'
const ROOM_NOT_EXIST = 'ROOM_NOT_EXIST'
const GET_CUSTOMER_BY_OWNER_FAILED = 'GET_CUSTOMER_BY_OWNER_FAILED'
const GET_CUSTOMER_BY_ID_FAILED = 'GET_CUSTOMER_BY_ID_FAILED'
const UPDATE_CUSTOMER_FAILED = 'UPDATE_CUSTOMER_FAILED'
const EMAIL_IS_EXIST = 'EMAIL_IS_EXIST'
const DELETE_CUSTOMER_FAILED = 'DELETE_CUSTOMER_FAILED'

module.exports = {
    CREATE_CUSTOMER_FAILED,
    ROOM_IS_FULL,
    ROOM_NOT_EXIST,
    GET_CUSTOMER_BY_OWNER_FAILED,
    GET_CUSTOMER_BY_ID_FAILED,
    UPDATE_CUSTOMER_FAILED,
    EMAIL_IS_EXIST,
    DELETE_CUSTOMER_FAILED
}