const PASSWORD_LEAST_6_CHARACTERS = 'PASSWORD_LEAST_6_CHARACTERS'
const PASSWORD_MAX_32_CHARACTERS = 'PASSWORD_MAX_32_CHARACTERS'
const EMAIL_IS_EXIST = 'EMAIL_IS_EXIST'
const CREATE_USER_FAILED = 'CREATE_USER_FAILED'
const EMAIL_NOT_EXIST = 'EMAIL_NOT_EXIST'
const EMAIL_OR_PASSWORD_FALSE = 'EMAIL_OR_PASSWORD_FALSE'
const EMAIL_IS_CONFIRMED = 'EMAIL_IS_CONFIRMED'
const CONFIRM_EMAIL_FAILED = 'CONFIRM_EMAIL_FAILED'
const USER_NOT_EXIST = 'USER_NOT_EXIST'
const CURRENT_PASSWORD_FALSE = 'CURRENT_PASSWORD_FALSE'
const CHANGE_PASSWORD_FALSE = 'CHANGE_PASSWORD_FALSE'
const CHANGE_INFO_FAILED = 'CHANGE_INFO_FAILED'
const GET_USER_FAILED = 'GET_USER_FAILED'
const GET_PASSWORD_IN_MAIL = 'GET_PASSWORD_IN_MAIL'
const LOGIN_FAILED = 'LOGIN_FAILED'

module.exports = {
    PASSWORD_LEAST_6_CHARACTERS,
    PASSWORD_MAX_32_CHARACTERS,
    EMAIL_IS_EXIST,
    CREATE_USER_FAILED,
    EMAIL_NOT_EXIST,
    EMAIL_OR_PASSWORD_FALSE,
    EMAIL_IS_CONFIRMED,
    CONFIRM_EMAIL_FAILED,
    USER_NOT_EXIST,
    CURRENT_PASSWORD_FALSE,
    CHANGE_PASSWORD_FALSE,
    CHANGE_INFO_FAILED,
    GET_USER_FAILED,
    GET_PASSWORD_IN_MAIL,
    LOGIN_FAILED
}