const CREATE_BLOCK_FAILED = 'CREATE_BLOCK_FAILED'
const NAME_BLOCK_EXIST = 'NAME_BLOCK_EXIST'
const GET_BLOCKS_BY_OWNER_FAILED = 'GET_BLOCKS_BY_OWNER_FAILED'
const GET_BLOCKS_BY_ID_FAILED = 'GET_BLOCKS_BY_ID_FAILED'
const UPDATE_BLOCK_FAILED = 'UPDATE_BLOCK_FAILED'
const DELETE_BLOCK_FAILED = 'DELETE_BLOCK_FAILED'

module.exports = {
    CREATE_BLOCK_FAILED,
    NAME_BLOCK_EXIST,
    GET_BLOCKS_BY_OWNER_FAILED,
    GET_BLOCKS_BY_ID_FAILED,
    UPDATE_BLOCK_FAILED,
    DELETE_BLOCK_FAILED
}