const CREATE_BILL_FAILED = 'CREATE_BILL_FAILED'
const CUSTOMER_NOT_IN_ROOM = 'CUSTOMER_NOT_IN_ROOM'
const ROOM_NOT_EXIST ='ROOM_NOT_EXIST'
const PRICE_OF_ROOM_FALSE = 'PRICE_OF_ROOM_FALSE'
const SERVICE_DETAIL_NOT_OF_ROOM = 'SERVICE_DETAIL_NOT_OF_ROOM'
const SERVICES_TOTAL_AMOUNT_FALSE = 'SERVICES_TOTAL_AMOUNT_FALSE'
const BILL_MUST_LEAST_1_CUSTOMER = 'BILL_MUST_LEAST_1_CUSTOMER'
const ROOM_TOTAL_AMOUNT_FALSE = 'ROOM_TOTAL_AMOUNT_FALSE'
const BILL_TOTAL_AMOUNT_FALSE = 'BILL_TOTAL_AMOUNT_FALSE'
const GET_BILLS_BY_OWNER_FAILED = 'GET_BILLS_BY_OWNER_FAILED'
const GET_BILLS_BY_CUSTOMER_FAILED = 'GET_BILLS_BY_CUSTOMER_FAILED'
const GET_BILLS_BY_ROOM_FAILED = 'GET_BILLS_BY_ROOM_FAILED'
const GET_BILLS_BY_ID_FAILED = 'GET_BILLS_BY_ID_FAILED'
const CANNOT_EDIT_BILL_IS_PAID = 'CANNOT_EDIT_BILL_IS_PAID'
const UPDATE_BILL_FAILED = 'UPDATE_BILL_FAILED'
const DELETE_BILL_FAILED = 'DELETE_BILL_FAILED'
const CANNOT_DELETE_BILL_PAID_ONE_DAY = 'CANNOT_DELETE_BILL_PAID_ONE_DAY'

module.exports = {
    CREATE_BILL_FAILED,
    CUSTOMER_NOT_IN_ROOM,
    ROOM_NOT_EXIST,
    PRICE_OF_ROOM_FALSE,
    SERVICE_DETAIL_NOT_OF_ROOM,
    BILL_MUST_LEAST_1_CUSTOMER,
    ROOM_TOTAL_AMOUNT_FALSE,
    SERVICES_TOTAL_AMOUNT_FALSE,
    BILL_TOTAL_AMOUNT_FALSE,
    GET_BILLS_BY_OWNER_FAILED,
    GET_BILLS_BY_CUSTOMER_FAILED,
    GET_BILLS_BY_ROOM_FAILED,
    GET_BILLS_BY_ID_FAILED,
    CANNOT_EDIT_BILL_IS_PAID,
    UPDATE_BILL_FAILED,
    DELETE_BILL_FAILED,
    CANNOT_DELETE_BILL_PAID_ONE_DAY
}